-- Partitioned tables info
SELECT TABLE_NAME, PARTITION_NAME, PARTITION_EXPRESSION, PARTITION_DESCRIPTION,
    TABLE_ROWS,
    ROUND(DATA_LENGTH / (1024 * 1024), 2) AS DATA_SIZE_MB,
    ROUND(INDEX_LENGTH / (1024 * 1024), 2) AS INDEX_SIZE_MB,
    ROUND((DATA_LENGTH + INDEX_LENGTH) / (1024 * 1024), 2) AS TOTAL_SIZE_MB
FROM information_schema.PARTITIONS
WHERE TABLE_SCHEMA=DATABASE()
AND PARTITION_NAME IS NOT NULL
ORDER BY TABLE_NAME, PARTITION_ORDINAL_POSITION;
