-- The biggest tables
SELECT TABLE_SCHEMA, TABLE_NAME, ENGINE,
    TABLE_ROWS,
    CONCAT(ROUND(DATA_LENGTH / (1024 * 1024), 2), 'M') AS DATA_LENGTH,
    CONCAT(ROUND(INDEX_LENGTH / (1024 * 1024), 2), 'M') AS INDEX_LENGTH,
    CONCAT(ROUND((DATA_LENGTH + INDEX_LENGTH) / (1024 * 1024), 2), 'M') AS TOTAL_SIZE
FROM information_schema.TABLES
WHERE TABLE_SCHEMA=DATABASE() -- the current database
ORDER BY TOTAL_SIZE DESC
LIMIT 10;
