-- The biggest tables
SELECT TABLE_SCHEMA, TABLE_NAME, ENGINE,
    TABLE_ROWS,
    ROUND(DATA_LENGTH / (1024 * 1024), 2) AS DATA_SIZE_MB,
    ROUND(INDEX_LENGTH / (1024 * 1024), 2) AS INDEX_SIZE_MB,
    ROUND((DATA_LENGTH + INDEX_LENGTH) / (1024 * 1024), 2) AS TOTAL_SIZE_MB
FROM information_schema.TABLES
WHERE TABLE_SCHEMA=DATABASE() -- the current schema only
ORDER BY TOTAL_SIZE_MB DESC
LIMIT 10;
